namespace webApi.Domain.Exceptions;

public enum ErrorCode
{
    ProductNotFound,
    PRODUCT_PRICE_INVALID,
    PRODUCT_NAME_REQUIRED,
    ACCOUNT_NOT_FOUND,
    PASSWORD_ERROR,
    SECRETKEY_NOT_FOUND,
    EXPIRESECONDS_NOT_FOUND,
    EMAIL_EXISTED,
    INCORRECT_PASSWORD,
    INCORRECT_EMAIL,
    OLD_PASSWORD_ERROR,
    REFRESH_TOKEN_INVALID
}